name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: Run a sample command
        run: echo "Utomation is successful!"
